import { SpriteFrameDef } from '@/types/spriteFrameDef'

export const spriteFrameDefs = {
  blob_twitch_0: {
    src: 'enemies.png',
    x: 92,
    y: 247,
    w: 16,
    h: 12,
    offsetX: 8,
    offsetY: -12,
  },
  blob_twitch_1: {
    src: 'enemies.png',
    x: 46,
    y: 247,
    w: 14,
    h: 12,
    offsetX: 7,
    offsetY: -12,
  },
  blob_idle: {
    src: 'enemies.png',
    x: 0,
    y: 247,
    w: 14,
    h: 13,
    offsetX: 7,
    offsetY: -13,
  },
  boomeranger_attack_high_0: {
    src: 'enemies.png',
    x: 56,
    y: 80,
    w: 16,
    h: 32,
    offsetX: 8,
    offsetY: -33,
  },
  boomeranger_walk_1: {
    src: 'enemies.png',
    x: 103,
    y: 32,
    w: 16,
    h: 32,
    offsetX: 8,
    offsetY: -32,
  },
  boomeranger_attack_low_0: {
    src: 'enemies.png',
    x: 72,
    y: 80,
    w: 16,
    h: 32,
    offsetX: 8,
    offsetY: -32,
  },
  boomeranger_attack_low_1: {
    src: 'enemies.png',
    x: 197,
    y: 0,
    w: 16,
    h: 31,
    offsetX: 8,
    offsetY: -31,
  },
  boomeranger_walk_0: {
    src: 'enemies.png',
    x: 159,
    y: 144,
    w: 16,
    h: 31,
    offsetX: 8,
    offsetY: -31,
  },
  bubble_default_0: {
    src: 'enemies.png',
    x: 248,
    y: 247,
    w: 8,
    h: 8,
    offsetX: 4,
    offsetY: -8,
  },
  deeler_attack_0: {
    src: 'enemies.png',
    x: 144,
    y: 207,
    w: 16,
    h: 16,
    offsetX: 8,
    offsetY: -16,
  },
  deeler_attack_1: {
    src: 'enemies.png',
    x: 128,
    y: 207,
    w: 16,
    h: 16,
    offsetX: 8,
    offsetY: -16,
  },
  deeler_canopy_0: {
    src: 'enemies.png',
    x: 112,
    y: 207,
    w: 16,
    h: 16,
    offsetX: 8,
    offsetY: -16,
  },
  deeler_canopy_1: {
    src: 'enemies.png',
    x: 96,
    y: 207,
    w: 16,
    h: 16,
    offsetX: 8,
    offsetY: -16,
  },
  explosion_default_0: {
    src: 'enemies.png',
    x: 196,
    y: 247,
    w: 10,
    h: 10,
    offsetX: 5,
    offsetY: -10,
  },
  explosion_default_1: {
    src: 'enemies.png',
    x: 206,
    y: 247,
    w: 10,
    h: 10,
    offsetX: 5,
    offsetY: -10,
  },
  explosion_default_2: {
    src: 'enemies.png',
    x: 237,
    y: 176,
    w: 16,
    h: 16,
    offsetX: 8,
    offsetY: -16,
  },
  explosion_default_3: {
    src: 'enemies.png',
    x: 237,
    y: 160,
    w: 16,
    h: 16,
    offsetX: 8,
    offsetY: -16,
  },
  fairy_default_0: {
    src: 'enemies.png',
    x: 262,
    y: 30,
    w: 8,
    h: 15,
    offsetX: 4,
    offsetY: -15,
  },
  fairy_default_1: {
    src: 'enemies.png',
    x: 255,
    y: 45,
    w: 8,
    h: 15,
    offsetX: 4,
    offsetY: -15,
  },
  fireball_burn_0: {
    src: 'enemies.png',
    x: 237,
    y: 222,
    w: 8,
    h: 10,
    offsetX: 4,
    offsetY: -10,
  },
  fireball_burn_1: {
    src: 'enemies.png',
    x: 245,
    y: 222,
    w: 8,
    h: 10,
    offsetX: 4,
    offsetY: -10,
  },
  fireball_burn_2: {
    src: 'enemies.png',
    x: 188,
    y: 247,
    w: 8,
    h: 10,
    offsetX: 4,
    offsetY: -10,
  },
  hammer_thrower_default_0: {
    src: 'enemies.png',
    x: 32,
    y: 112,
    w: 16,
    h: 32,
    offsetX: 8,
    offsetY: -32,
  },
  hammer_thrower_default_1: {
    src: 'enemies.png',
    x: 197,
    y: 124,
    w: 16,
    h: 31,
    offsetX: 8,
    offsetY: -30,
  },
  hammer_thrower_throw_0: {
    src: 'enemies.png',
    x: 48,
    y: 112,
    w: 20,
    h: 32,
    offsetX: 12,
    offsetY: -32,
  },
  hammer_thrower_throw_1: {
    src: 'enemies.png',
    x: 0,
    y: 176,
    w: 20,
    h: 31,
    offsetX: 12,
    offsetY: -30,
  },
  heart_container_idle_0: {
    src: 'enemies.png',
    x: 255,
    y: 60,
    w: 16,
    h: 15,
    offsetX: 8,
    offsetY: -15,
  },
  key_idle_0: {
    src: 'enemies.png',
    x: 263,
    y: 45,
    w: 8,
    h: 15,
    offsetX: 4,
    offsetY: -15,
  },
  lizardpuppy_idle_0: {
    src: 'enemies.png',
    x: 73,
    y: 65,
    w: 22,
    h: 15,
    offsetX: -2,
    offsetY: -7,
    // offsetXFlipped: 0
  },
  lizardpuppy_walk_0: {
    src: 'enemies.png',
    x: 0,
    y: 232,
    w: 24,
    h: 15,
    offsetX: 0,
    offsetY: -7,
    // offsetXFlipped: 0
  },
  lizardpuppy_stand_0: {
    src: 'enemies.png',
    x: 134,
    y: 176,
    w: 16,
    h: 29,
    offsetX: 0,
    offsetY: -29,
    // offsetXFlipped: 0
  },
  octorok_idle_0: {
    src: 'enemies.png',
    x: 208,
    y: 207,
    w: 16,
    h: 16,
    offsetX: 8,
    offsetY: -16,
  },
  octorok_idle_1: {
    src: 'enemies.png',
    x: 192,
    y: 207,
    w: 16,
    h: 16,
    offsetX: 8,
    offsetY: -16,
  },
  proj_hammer_default_0: {
    src: 'enemies.png',
    x: 116,
    y: 247,
    w: 8,
    h: 11,
    offsetX: 4,
    offsetY: -11,
  },
  proj_hammer_default_1: {
    src: 'enemies.png',
    x: 108,
    y: 247,
    w: 8,
    h: 11,
    offsetX: 4,
    offsetY: -11,
  },
  proj_hammer_default_2: {
    src: 'enemies.png',
    x: 124,
    y: 247,
    w: 8,
    h: 11,
    offsetX: 4,
    offsetY: -11,
  },
  proj_hammer_default_3: {
    src: 'enemies.png',
    x: 132,
    y: 247,
    w: 8,
    h: 11,
    offsetX: 4,
    offsetY: -11,
  },
  scorpy_example_0: {
    src: 'enemies.png',
    x: 182,
    y: 176,
    w: 24,
    h: 27,
    offsetX: 0,
    offsetY: -13,
    // offsetXFlipped: 0
  },
  scorpy_example_1: {
    src: 'enemies.png',
    x: 213,
    y: 0,
    w: 24,
    h: 27,
    offsetX: 0,
    offsetY: -13,
    // offsetXFlipped: 0
  },
  scorpy_example_2: {
    src: 'enemies.png',
    x: 213,
    y: 27,
    w: 24,
    h: 27,
    offsetX: 0,
    offsetY: -13,
    // offsetXFlipped: 0
  },
  scorpy_example_3: {
    src: 'enemies.png',
    x: 213,
    y: 54,
    w: 24,
    h: 27,
    offsetX: 0,
    offsetY: -13,
    // offsetXFlipped: 0
  },
  scorpy_example_4: {
    src: 'enemies.png',
    x: 213,
    y: 158,
    w: 24,
    h: 25,
    offsetX: 0,
    offsetY: -10,
    // offsetXFlipped: 0
  },
  scorpy_example_5: {
    src: 'enemies.png',
    x: 0,
    y: 207,
    w: 24,
    h: 25,
    offsetX: 0,
    offsetY: -10,
    // offsetXFlipped: 0
  },
  skeleton_attack_0: {
    src: 'enemies.png',
    x: 94,
    y: 144,
    w: 16,
    h: 32,
    offsetX: 8,
    offsetY: -32,
  },
  skeleton_attack_1: {
    src: 'enemies.png',
    x: 110,
    y: 144,
    w: 16,
    h: 32,
    offsetX: 8,
    offsetY: -32,
  },
  skeleton_attack_2: {
    src: 'enemies.png',
    x: 126,
    y: 144,
    w: 33,
    h: 32,
    offsetX: 8,
    offsetY: -32,
    // offsetXFlipped: 46
  },
  skeleton_walk_0: {
    src: 'enemies.png',
    x: 62,
    y: 144,
    w: 16,
    h: 32,
    offsetX: 8,
    offsetY: -32,
  },
  skeleton_jump_0: {
    src: 'enemies.png',
    x: 213,
    y: 81,
    w: 16,
    h: 27,
    offsetX: 8,
    offsetY: -29,
  },
  skeleton_walk_1: {
    src: 'enemies.png',
    x: 78,
    y: 144,
    w: 16,
    h: 32,
    offsetX: 8,
    offsetY: -32,
  },
  proj_boomerang_default_0: {
    src: 'enemies.png',
    x: 190,
    y: 120,
    w: 7,
    h: 8,
    offsetX: 3,
    offsetY: -8,
  },
  proj_boomerang_default_1: {
    src: 'enemies.png',
    x: 96,
    y: 223,
    w: 7,
    h: 8,
    offsetX: 3,
    offsetY: -8,
  },
  elevator_default_0: {
    src: 'player.png',
    x: 56,
    y: 64,
    w: 24,
    h: 8,
    offsetX: 12,
    offsetY: -8,
  },
  link_attack_0: {
    src: 'player.png',
    x: 16,
    y: 32,
    w: 23,
    h: 32,
    offsetX: 15,
    offsetY: -33,
  },
  link_attack_1: {
    src: 'player.png',
    x: 64,
    y: 0,
    w: 32,
    h: 30,
    offsetX: 8,
    offsetY: -30,
  },
  link_stand_0: {
    src: 'player.png',
    x: 32,
    y: 0,
    w: 16,
    h: 32,
    offsetX: 8,
    offsetY: -33,
  },
  link_collect_0: {
    src: 'player.png',
    x: 0,
    y: 0,
    w: 16,
    h: 32,
    offsetX: 8,
    offsetY: -33,
  },
  link_crouch_0: {
    src: 'player.png',
    x: 0,
    y: 64,
    w: 16,
    h: 27,
    offsetX: 8,
    offsetY: -30,
  },
  link_crouch_attack_0: {
    src: 'player.png',
    x: 16,
    y: 64,
    w: 32,
    h: 26,
    offsetX: 8,
    offsetY: -24,
  },
  link_hurt_0: {
    src: 'player.png',
    x: 80,
    y: 30,
    w: 16,
    h: 29,
    offsetX: 8,
    offsetY: -28,
  },
  link_walk_0: {
    src: 'player.png',
    x: 48,
    y: 0,
    w: 16,
    h: 32,
    offsetX: 8,
    offsetY: -33,
  },
  link_walk_1: {
    src: 'player.png',
    x: 0,
    y: 32,
    w: 16,
    h: 32,
    offsetX: 8,
    offsetY: -33,
  },
  link_walk_2: {
    src: 'player.png',
    x: 39,
    y: 32,
    w: 16,
    h: 31,
    offsetX: 9,
    offsetY: -32,
  },
  lock_default_0: {
    src: 'player.png',
    x: 48,
    y: 64,
    w: 8,
    h: 16,
    offsetX: 4,
    offsetY: -16,
  },
  lock_wall_0: {
    src: 'player.png',
    x: 55,
    y: 32,
    w: 8,
    h: 16,
    offsetX: 4,
    offsetY: -16,
  },
  owblob_default_0: {
    src: 'overworld.png',
    x: 9,
    y: 48,
    w: 11,
    h: 9,
    offsetX: -3,
    offsetY: 0,
    // offsetXFlipped: -6
  },
  owblob_default_1: {
    src: 'overworld.png',
    x: 0,
    y: 48,
    w: 9,
    h: 10,
    offsetX: -4,
    offsetY: -2,
    // offsetXFlipped: -8
  },
  owplayer_raft_0: {
    src: 'overworld.png',
    x: 38,
    y: 0,
    w: 16,
    h: 16,
    offsetX: 0,
    offsetY: -8,
    // offsetXFlipped: 0
  },
  owplayer_stand_0: {
    src: 'overworld.png',
    x: 31,
    y: 32,
    w: 7,
    h: 15,
    offsetX: -5,
    offsetY: -7,
    // offsetXFlipped: -10
  },
  owplayer_walk_east_0: {
    src: 'overworld.png',
    x: 23,
    y: 32,
    w: 8,
    h: 15,
    offsetX: -4,
    offsetY: -7,
    // offsetXFlipped: -10
  },
  owplayer_walk_east_1: {
    src: 'overworld.png',
    x: 15,
    y: 32,
    w: 8,
    h: 16,
    offsetX: -4,
    offsetY: -8,
    // offsetXFlipped: -10
  },
  owplayer_walk_north_0: {
    src: 'overworld.png',
    x: 16,
    y: 16,
    w: 7,
    h: 16,
    offsetX: -5,
    offsetY: -8,
    // offsetXFlipped: -10
  },
  owplayer_walk_north_1: {
    src: 'overworld.png',
    x: 38,
    y: 16,
    w: 7,
    h: 16,
    offsetX: -5,
    offsetY: -8,
    // offsetXFlipped: -10
  },
  owplayer_walk_south_0: {
    src: 'overworld.png',
    x: 7,
    y: 0,
    w: 7,
    h: 16,
    offsetX: -5,
    offsetY: -8,
    // offsetXFlipped: -10
  },
  owplayer_walk_south_1: {
    src: 'overworld.png',
    x: 0,
    y: 0,
    w: 7,
    h: 16,
    offsetX: -5,
    offsetY: -8,
    // offsetXFlipped: -10
  },
  owmonster_default_0: {
    src: 'overworld.png',
    x: 23,
    y: 16,
    w: 15,
    h: 16,
    offsetX: 0,
    offsetY: -8,
    // offsetXFlipped: 0
  },
  owmonster_default_1: {
    src: 'overworld.png',
    x: 0,
    y: 32,
    w: 15,
    h: 16,
    offsetX: 0,
    offsetY: -8,
    // offsetXFlipped: 0
  },
  owfairy_default_0: {
    src: 'overworld.png',
    x: 54,
    y: 0,
    w: 8,
    h: 15,
    offsetX: -4,
    offsetY: -7,
    // offsetXFlipped: -8
  },
  owfairy_default_1: {
    src: 'overworld.png',
    x: 46,
    y: 32,
    w: 8,
    h: 15,
    offsetX: -4,
    offsetY: -7,
    // offsetXFlipped: -8
  },
} as const satisfies Record<string, SpriteFrameDef>
