// {{include "@/templates/classMap.ts.hbs" identifier="playerStrategyFsmClassMap" files=(readdir "." "*.ts")}}

// ===================== GENERATED CODE BELOW =====================
// Generated by @chriswa/ts-codegen (embedded template)
// Do not edit manually - changes will be overwritten
// ================================================================
import { AirborneStrategy } from './airborneStrategy'
import { AttackStrategy } from './attackStrategy'
import { GroundedStrategy } from './groundedStrategy'
import { HurtStrategy } from './hurtStrategy'

export const playerStrategyFsmClassMap = {
  AirborneStrategy,
  AttackStrategy,
  GroundedStrategy,
  HurtStrategy,
} as const
