// {{include "@/templates/classMapKeys.ts.hbs" identifier="PlayerStrategyFsmClassMapKeys" files=(readdir "." "*.ts")}}

// ===================== GENERATED CODE BELOW =====================
// Generated by @chriswa/ts-codegen (embedded template)
// Do not edit manually - changes will be overwritten
// ================================================================
export type PlayerStrategyFsmClassMapKeys =
  | 'AirborneStrategy'
  | 'AttackStrategy'
  | 'GroundedStrategy'
  | 'HurtStrategy'
